Repository Codepath-SITE-Workday9/BugTracker, pull requests merged in 2022-07, with the labels that each got.

#29 List tickets
  bugtracker-api/models/ticket.js
  bugtracker-api/routes/ticket.js
  planning/project_plan.md
Labels: enhancement

#41 Fetch ticket details
  bugtracker-api/models/ticket.js
  bugtracker-api/routes/ticket.js
  planning/project_plan.md
Labels: enhancement

#42 Create comment
  bugtracker-api/models/ticket.js
  bugtracker-api/routes/ticket.js
Labels: enhancement

#43 Delete comment
  bugtracker-api/models/ticket.js
Labels: enhancement

#45 Update comment
  bugtracker-api/models/ticket.js
  bugtracker-api/routes/ticket.js
  planning/project_plan.md
Labels: enhancement

#49 Test auth routes
  bugtracker-api/app.test.js
  bugtracker-api/config.js
  bugtracker-api/models/user.js
  bugtracker-api/package-lock.json
  bugtracker-api/package.json
  bugtracker-api/routes/auth.js
  planning/project_plan.md
Labels: enhancement

#51 Test tokens
  bugtracker-api/utils/tokens.test.js
Labels: testing

#52 Fixed bug when loading the page due to dependency issues
  bugtracker-ui/package.json
  bugtracker-ui/vite.config.js
Labels: bug

#53 Fixed bug causing dashboard charts to not load initially
  bugtracker-ui/src/components/Dashboard/Dashboard.jsx
  bugtracker-ui/src/services/charts.js
Labels: bug

#54 Test auth register
  bugtracker-api/models/user.test.js
  bugtracker-api/tests/common.js
Labels: testing

#56 Test auth me
  bugtracker-api/middleware/security.test.js
  bugtracker-api/models/user.test.js
  bugtracker-api/routes/auth.test.js
Labels: testing

#55 Connecting teamspage to backend
  bugtracker-api/models/user.js
  bugtracker-api/routes/auth.js
  bugtracker-api/routes/team.js
  bugtracker-api/routes/ticket.js
  bugtracker-ui/src/components/App/App.jsx
  bugtracker-ui/src/components/Dropdown/SortByDropdown/SortByDropdown.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectView/ProjectView.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectsOverview/ProjectsOverview.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectsPage.jsx
  bugtracker-ui/src/components/RegisterPage/RegisterForm/RegisterForm.jsx
  bugtracker-ui/src/components/TeamsPage/TeamCard/TeamCard.jsx
  bugtracker-ui/src/components/TeamsPage/TeamModal/TeamModal.css
  bugtracker-ui/src/components/TeamsPage/TeamModal/TeamModal.jsx
  bugtracker-ui/src/components/TeamsPage/TeamView/TeamView.css
  bugtracker-ui/src/components/TeamsPage/TeamView/TeamView.jsx
  bugtracker-ui/src/components/TeamsPage/TeamsOverview/TeamsOverview.css
  bugtracker-ui/src/components/TeamsPage/TeamsOverview/TeamsOverview.jsx
  bugtracker-ui/src/components/TeamsPage/TeamsPage.css
  bugtracker-ui/src/components/TeamsPage/TeamsPage.jsx
  bugtracker-ui/src/contexts/auth.jsx
  bugtracker-ui/src/contexts/team.jsx
  bugtracker-ui/src/hooks/useLoginForm.js
  bugtracker-ui/src/services/apiClient.js
Labels: enhancement

#57 Test teams routes
  bugtracker-api/models/teams.test.js
Labels: testing

#58 Update database
  bugtracker-api/bugtracker-schema.sql
  bugtracker-api/models/teams.test.js
  bugtracker-api/models/user.js
  bugtracker-api/models/user.test.js
  bugtracker-api/routes/auth.test.js
Labels: enhancement

#59 Added modals into dashboard tables
  bugtracker-ui/src/components/Dashboard/Dashboard.css
  bugtracker-ui/src/components/Dashboard/Dashboard.jsx
  bugtracker-ui/src/components/Dashboard/DashboardProjectsModal/DashboardProjectsModal.css
  bugtracker-ui/src/components/Dashboard/DashboardProjectsModal/DashboardProjectsModal.jsx
  bugtracker-ui/src/components/Dashboard/DashboardTeamsModal/DashboardTeamsModal.css
  bugtracker-ui/src/components/Dashboard/DashboardTeamsModal/DashboardTeamsModal.jsx
  bugtracker-ui/src/components/Tables/DashboardProjectsTable.jsx
  bugtracker-ui/src/components/Tables/DashboardTeamsTable.jsx
  bugtracker-ui/src/components/Tables/TableProperties.css
Labels: enhancement

#60 User statistics feature
  bugtracker-api/app.js
  bugtracker-api/models/statistics.js
  bugtracker-api/routes/report.js
Labels: enhancement

#62 Updated the projects model
  bugtracker-api/models/projects.js
  bugtracker-ui/package.json
Labels: bug

#61 Connect ProjectsPage to backend
  bugtracker-api/models/user.js
  bugtracker-api/routes/team.js
  bugtracker-ui/src/components/App/App.jsx
  bugtracker-ui/src/components/Dropdown/AddProjectsDropdown/AddProjectsDropdown.jsx
  bugtracker-ui/src/components/Dropdown/AddTeamsDropdown/AddTeamsDropdown.css
  bugtracker-ui/src/components/Dropdown/AddTeamsDropdown/AddTeamsDropdown.jsx
  bugtracker-ui/src/components/Modals/ProjectModal/ProjectModal.css
  bugtracker-ui/src/components/Modals/ProjectModal/ProjectModal.jsx
  bugtracker-ui/src/components/Modals/TeamModal/TeamModal.css
  bugtracker-ui/src/components/Modals/TeamModal/TeamModal.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectCard/ProjectCard.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectModal/ProjectModal.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectView/ProjectView.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectsOverview/ProjectsOverview.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectsPage.jsx
  bugtracker-ui/src/components/TeamsPage/TeamView/TeamView.jsx
  bugtracker-ui/src/components/TeamsPage/TeamsOverview/TeamsOverview.jsx
  bugtracker-ui/src/components/TeamsPage/TeamsPage.jsx
  bugtracker-ui/src/contexts/project.jsx
  bugtracker-ui/src/contexts/team.jsx
  bugtracker-ui/src/hooks/useProjectForm.js
  bugtracker-ui/src/hooks/useTeamForm.js
  bugtracker-ui/src/services/apiClient.js
Labels: enhancement

#63 Connect dashboard to backend
  bugtracker-ui/src/components/Dashboard/Dashboard.css
  bugtracker-ui/src/components/Dashboard/Dashboard.jsx
  bugtracker-ui/src/services/charts.js
Labels: enhancement

#64 Create profile
  bugtracker-ui/src/components/LandingPage/LandingPage.css
  bugtracker-ui/src/components/LandingPage/LandingPage.jsx
  bugtracker-ui/src/components/LandingPage/NoUserNavbar/NoUserNavbar.css
  bugtracker-ui/src/components/UserProfile/UserProfile.css
  bugtracker-ui/src/components/UserProfile/UserProfile.jsx
Labels: enhancement

#66 Dashboard modal backend
  bugtracker-ui/src/components/Dashboard/Dashboard.jsx
  bugtracker-ui/src/components/Tables/DashboardProjectsTable.jsx
  bugtracker-ui/src/components/Tables/DashboardTeamsTable.jsx
  bugtracker-ui/src/services/apiClient.js
  bugtracker-ui/src/services/charts.js
Labels: enhancement

#67 Table styling
  bugtracker-api/models/teams.js
  bugtracker-api/routes/team.js
  bugtracker-ui/src/components/Dashboard/Dashboard.jsx
  bugtracker-ui/src/components/Dashboard/DashboardTeamsModal/DashboardTeamsModal.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectsOverview/ProjectsOverview.jsx
  bugtracker-ui/src/components/Tables/TeamsPageDevelopersTable.jsx
  bugtracker-ui/src/components/Tables/TeamsPageProjectsTable.jsx
  bugtracker-ui/src/components/TeamsPage/TeamView/TeamView.jsx
  bugtracker-ui/src/components/TeamsPage/TeamsOverview/TeamsOverview.jsx
  bugtracker-ui/src/components/UserProfile/UserProfile.css
  bugtracker-ui/src/services/apiClient.js
Labels: enhancement

#68 Tables to profile
  bugtracker-api/models/user.js
  bugtracker-ui/src/components/LandingPage/LandingPage.css
  bugtracker-ui/src/components/LandingPage/LandingPage.jsx
  bugtracker-ui/src/components/LandingPage/NoUserNavbar/NoUserNavbar.css
  bugtracker-ui/src/components/LoginPage/LoginForm/LoginForm.css
  bugtracker-ui/src/components/LoginPage/LoginPage.css
  bugtracker-ui/src/components/RegisterPage/RegisterPage.css
  bugtracker-ui/src/components/UserProfile/UserProfile.css
  bugtracker-ui/src/components/UserProfile/UserProfile.jsx
  bugtracker-ui/src/services/charts.js
Labels: enhancement

#69 Answer Reflection 2 Questions
  reflections/reflection2.md
Labels: documentation
