Repository Codepath-SITE-Workday9/BugTracker, pull requests merged in 2022-08, with the labels that each got.

#74 ProjectsPage styling and minor additional styling to Sidebar
  bugtracker-api/models/projects.js
  bugtracker-api/models/teams.js
  bugtracker-ui/src/components/LandingPage/LandingPage.jsx
  bugtracker-ui/src/components/Modals/ProjectModal/ProjectModal.jsx
  bugtracker-ui/src/components/Modals/TeamModal/TeamModal.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectView/ProjectView.css
  bugtracker-ui/src/components/ProjectsPage/ProjectView/ProjectView.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectsOverview/ProjectsOverview.css
  bugtracker-ui/src/components/ProjectsPage/ProjectsOverview/ProjectsOverview.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectsPage.jsx
  bugtracker-ui/src/components/Sidebar/Sidebar.css
  bugtracker-ui/src/components/Sidebar/Sidebar.jsx
  bugtracker-ui/src/components/Tables/TeamsPageProjectsTable.jsx
  bugtracker-ui/src/components/TeamsPage/TeamView/TeamView.css
  bugtracker-ui/src/components/TeamsPage/TeamView/TeamView.jsx
  bugtracker-ui/src/components/TeamsPage/TeamsOverview/TeamsOverview.css
  bugtracker-ui/src/components/TeamsPage/TeamsOverview/TeamsOverview.jsx
  bugtracker-ui/src/services/apiClient.js
Labels: enhancement

#76 Charts to profile
  bugtracker-api/models/projects.js
  bugtracker-ui/src/components/LandingPage/LandingPage.css
  bugtracker-ui/src/components/LandingPage/LandingPage.jsx
  bugtracker-ui/src/components/LoginPage/LoginForm/LoginForm.css
  bugtracker-ui/src/components/Navbar/Navbar.css
  bugtracker-ui/src/components/RegisterPage/RegisterForm/RegisterForm.css
  bugtracker-ui/src/components/UserProfile/UserProfile.css
  bugtracker-ui/src/components/UserProfile/UserProfile.jsx
  bugtracker-ui/src/services/charts.js
  bugtracker-ui/src/services/userCharts.js
Labels: bug, enhancement

#77 User profile
  bugtracker-api/models/statistics.js
  bugtracker-api/models/teams.js
  bugtracker-api/routes/report.js
  bugtracker-api/routes/team.js
  bugtracker-ui/src/components/LandingPage/LandingPage.jsx
  bugtracker-ui/src/components/UserProfile/UserProfile.jsx
Labels: bug, enhancement

#78 Dashboard teams table shows teams with names
  bugtracker-ui/src/components/Dashboard/Dashboard.jsx
  bugtracker-ui/src/components/Tables/DashboardTeamsTable.jsx
  bugtracker-ui/src/contexts/team.jsx
  bugtracker-ui/src/hooks/useTeamForm.js
  bugtracker-ui/src/main.jsx
Labels: bug, enhancement

#79 Updated the fetchMembersForMultipleTeams function to send back an arr…
  bugtracker-api/models/teams.js
  bugtracker-api/routes/team.js
Labels: bug, enhancement

#85 Created and implemented a new function on the backend to get all the …
  bugtracker-api/models/ticket.js
  bugtracker-api/routes/ticket.js
Labels: enhancement

#86 Ticketspage styling
  bugtracker-ui/src/components/Modals/TicketModal/TicketModal.jsx
  bugtracker-ui/src/components/Tables/DashboardTeamsTable.jsx
  bugtracker-ui/src/components/Tables/TeamsPageDevelopersTable.jsx
  bugtracker-ui/src/components/TeamsPage/TeamView/TeamView.jsx
  bugtracker-ui/src/components/TicketsPage/TicketCard/TicketCard.jsx
  bugtracker-ui/src/components/TicketsPage/TicketView/TicketView.css
  bugtracker-ui/src/components/TicketsPage/TicketView/TicketView.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsOverview/TicketsOverview.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsPage.jsx
  bugtracker-ui/src/contexts/team.jsx
  bugtracker-ui/src/contexts/ticket.jsx
  bugtracker-ui/src/hooks/useTicketForm.js
  bugtracker-ui/src/services/apiClient.js
Labels: enhancement

#87 Connect profile charts to backend
  bugtracker-api/models/projects.js
  bugtracker-api/models/statistics.js
  bugtracker-api/routes/report.js
  bugtracker-ui/src/components/LandingPage/LandingPage.css
  bugtracker-ui/src/components/LandingPage/LandingPage.jsx
  bugtracker-ui/src/components/UserProfile/UserProfile.css
  bugtracker-ui/src/components/UserProfile/UserProfile.jsx
  bugtracker-ui/src/services/apiClient.js
  bugtracker-ui/src/services/userCharts.js
Labels: bug, enhancement

#88 Connect dashboard statistics
  bugtracker-ui/src/components/App/App.jsx
  bugtracker-ui/src/components/Dashboard/Dashboard.jsx
  bugtracker-ui/src/contexts/statistics.jsx
  bugtracker-ui/src/contexts/team.jsx
  bugtracker-ui/src/contexts/ticket.jsx
  bugtracker-ui/src/services/charts.js
Labels: bug, enhancement

#89 Updating TicketsPage
  bugtracker-ui/src/components/Modals/ProjectModal/ProjectModal.jsx
  bugtracker-ui/src/components/Modals/TicketModal/TicketModal.css
  bugtracker-ui/src/components/Modals/TicketModal/TicketModal.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectCard/ProjectCard.css
  bugtracker-ui/src/components/ProjectsPage/ProjectsPage.jsx
  bugtracker-ui/src/components/TeamsPage/TeamCard/TeamCard.css
  bugtracker-ui/src/components/TeamsPage/TeamsPage.jsx
  bugtracker-ui/src/components/TicketsPage/TicketCard/TicketCard.css
  bugtracker-ui/src/components/TicketsPage/TicketView/TicketView.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsOverview/TicketsOverview.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsPage.jsx
  bugtracker-ui/src/hooks/useTicketForm.js
  bugtracker-ui/src/services/apiClient.js
Labels: enhancement

#90 Tickets page bugfixes
  bugtracker-api/models/projects.js
  bugtracker-ui/src/components/Modals/TicketModal/TicketModal.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectsOverview/ProjectsOverview.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectsPage.jsx
  bugtracker-ui/src/components/Tables/TeamsPageProjectsTable.jsx
  bugtracker-ui/src/components/TeamsPage/TeamsPage.jsx
  bugtracker-ui/src/components/TicketsPage/TicketInfoBox/TicketInfoBox.css
  bugtracker-ui/src/components/TicketsPage/TicketInfoBox/TicketInfoBox.jsx
  bugtracker-ui/src/components/TicketsPage/TicketView/TicketView.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsOverview/TicketsOverview.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsPage.jsx
  bugtracker-ui/src/contexts/team.jsx
  bugtracker-ui/src/contexts/ticket.jsx
  bugtracker-ui/src/hooks/useTicketForm.js
  bugtracker-ui/src/services/apiClient.js
Labels: enhancement

#91 Fix charts
  bugtracker-api/models/projects.js
  bugtracker-ui/src/components/App/App.jsx
  bugtracker-ui/src/components/Dashboard/Dashboard.jsx
  bugtracker-ui/src/contexts/project.jsx
  bugtracker-ui/src/contexts/statistics.jsx
  bugtracker-ui/src/contexts/team.jsx
  bugtracker-ui/src/hooks/useProjectForm.js
Labels: bug

#92 Update landing styling
  bugtracker-ui/src/components/LandingPage/LandingPage.css
  bugtracker-ui/src/components/LandingPage/LandingPage.jsx
  bugtracker-ui/src/components/LandingPage/NoUserNavbar/NoUserNavbar.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectView/ProjectView.css
  bugtracker-ui/src/components/Sidebar/Sidebar.jsx
  bugtracker-ui/src/components/Tables/TableProperties.css
  bugtracker-ui/src/components/TeamsPage/TeamView/TeamView.css
  bugtracker-ui/src/components/UserProfile/UserProfile.css
  bugtracker-ui/src/components/UserProfile/UserProfile.jsx
Labels: enhancement

#93 Fixed bugs with creating & updating tickets
  bugtracker-ui/src/components/Modals/TicketModal/TicketModal.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsOverview/TicketsOverview.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsPage.jsx
  bugtracker-ui/src/contexts/ticket.jsx
  bugtracker-ui/src/hooks/useTicketForm.js
Labels: bug

#94 Fixed bug where a client has to send in user ids to update the member…
  bugtracker-api/models/ticket.js
Labels: bug, enhancement

#95 Fixed bug when loading tickets and added additional styling to tickets page
  bugtracker-api/models/ticket.js
  bugtracker-ui/src/components/Modals/TicketModal/TicketModal.jsx
  bugtracker-ui/src/components/TicketsPage/TicketView/TicketView.css
  bugtracker-ui/src/components/TicketsPage/TicketView/TicketView.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsOverview/TicketsOverview.css
  bugtracker-ui/src/components/TicketsPage/TicketsOverview/TicketsOverview.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsPage.jsx
  bugtracker-ui/src/contexts/project.jsx
  bugtracker-ui/src/contexts/statistics.jsx
  bugtracker-ui/src/contexts/team.jsx
  bugtracker-ui/src/hooks/useProjectForm.js
Labels: bug, enhancement

#100 TicketModal styling
  bugtracker-api/routes/ticket.js
  bugtracker-ui/src/components/Modals/TicketModal/TicketModal.css
  bugtracker-ui/src/components/Modals/TicketModal/TicketModal.jsx
  bugtracker-ui/src/services/apiClient.js
Labels: enhancement

#99 Create ticket projects page
  bugtracker-api/models/ticket.js
  bugtracker-api/routes/ticket.js
  bugtracker-ui/src/components/App/App.jsx
  bugtracker-ui/src/components/Dropdown/AddDevelopersDropdown/AddDevelopersDropdown.jsx
  bugtracker-ui/src/components/Modals/TicketModal/TicketModal.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectsPage.jsx
  bugtracker-ui/src/components/Tables/ProjectsPageTicketsTable.jsx
  bugtracker-ui/src/hooks/useTicketForm.js
  bugtracker-ui/src/services/apiClient.js
Labels: bug, enhancement

#101 Improved dashboard styling
  bugtracker-ui/src/components/Dashboard/Dashboard.css
  bugtracker-ui/src/components/Dashboard/Dashboard.jsx
Labels: enhancement

#102 Projects page styling
  bugtracker-ui/src/components/Dashboard/Dashboard.jsx
  bugtracker-ui/src/components/Dropdown/AddDevelopersDropdown/AddDevelopersDropdown.css
  bugtracker-ui/src/components/Dropdown/AddDevelopersDropdown/AddDevelopersDropdown.jsx
  bugtracker-ui/src/components/Modals/ProjectModal/ProjectModal.jsx
  bugtracker-ui/src/components/Modals/TicketModal/TicketModal.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectView/ProjectView.css
  bugtracker-ui/src/components/ProjectsPage/ProjectView/ProjectView.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectsOverview/ProjectsOverview.css
  bugtracker-ui/src/components/ProjectsPage/ProjectsOverview/ProjectsOverview.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectsPage.jsx
  bugtracker-ui/src/contexts/project.jsx
  bugtracker-ui/src/hooks/useProjectForm.js
  bugtracker-ui/src/services/apiClient.js
Labels: bug, enhancement

#103 Added additinal styling and added functions to clear
  bugtracker-api/models/ticket.js
  bugtracker-ui/src/components/Modals/TicketModal/TicketModal.css
  bugtracker-ui/src/components/Modals/TicketModal/TicketModal.jsx
  bugtracker-ui/src/components/Sidebar/Sidebar.jsx
  bugtracker-ui/src/components/TicketsPage/TicketView/TicketView.css
  bugtracker-ui/src/components/TicketsPage/TicketView/TicketView.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsOverview/TicketsOverview.css
  bugtracker-ui/src/components/TicketsPage/TicketsOverview/TicketsOverview.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsPage.css
  bugtracker-ui/src/contexts/auth.jsx
  bugtracker-ui/src/contexts/project.jsx
  bugtracker-ui/src/contexts/statistics.jsx
  bugtracker-ui/src/contexts/team.jsx
  bugtracker-ui/src/contexts/ticket.jsx
  bugtracker-ui/src/hooks/useTicketForm.js
Labels: enhancement

#104 Fix dropdown menus
  bugtracker-ui/src/components/Dropdown/AddProjectsDropdown/AddProjectsDropdown.jsx
  bugtracker-ui/src/components/Dropdown/AddTeamsDropdown/AddTeamsDropdown.jsx
  bugtracker-ui/src/components/LandingPage/LandingPage.jsx
  bugtracker-ui/src/components/Modals/ProjectModal/ProjectModal.jsx
  bugtracker-ui/src/components/Modals/TeamModal/TeamModal.jsx
  planning/project_plan.md
Labels: enhancement

#105 Table redirects
  bugtracker-ui/src/components/Tables/DashboardProjectsTable.jsx
Labels: enhancement

#107 Redeploying backend
  bugtracker-api/models/projects.js
  bugtracker-ui/src/components/App/App.jsx
  bugtracker-ui/src/constants.js
Labels: bug

#108 Updated fetchUserByEmail function to return a user with only the public user's information.
  bugtracker-api/models/user.js
Labels: bug

#109 Update bug in getProjectById function in Projects Model
  bugtracker-api/models/projects.js
Labels: bug

#110 Fixed bug in getTicketsForProjects funcction in tickets model
  bugtracker-api/models/ticket.js
Labels: bug

#111 Fixing table properties
  bugtracker-ui/src/components/Tables/ProjectsPageTicketsTable.jsx
Labels: enhancement

#115 Removed unused icons in sidebar/navbar and linked profile icon in nav…
  bugtracker-ui/src/components/Navbar/Navbar.css
  bugtracker-ui/src/components/Navbar/Navbar.jsx
  bugtracker-ui/src/components/Sidebar/Sidebar.jsx
Labels: enhancement

#117 Added skeleton for filters on tickets page
  bugtracker-ui/src/components/TicketsPage/TicketsOverview/TicketsOverview.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsPage.jsx
  bugtracker-ui/src/contexts/ticket.jsx
  bugtracker-ui/src/hooks/useTicketForm.js
Labels: enhancement

#118 Updating tickets list
  README.md
  bugtracker-ui/src/components/App/App.jsx
  bugtracker-ui/src/components/Dashboard/Dashboard.jsx
  bugtracker-ui/src/components/Modals/TicketModal/TicketModal.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectView/ProjectView.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectsPage.jsx
  bugtracker-ui/src/components/Tables/DashboardProjectsTable.jsx
  bugtracker-ui/src/components/Tables/DashboardTeamsTable.jsx
  bugtracker-ui/src/components/Tables/TicketsPageCollaboratorsTable.jsx
  bugtracker-ui/src/components/Tables/TicketsPageTicketsTable.jsx
  bugtracker-ui/src/components/TeamsPage/TeamView/TeamView.jsx
  bugtracker-ui/src/components/TicketsPage/TicketView/TicketView.css
  bugtracker-ui/src/components/TicketsPage/TicketView/TicketView.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsOverview/TicketsOverview.jsx
  bugtracker-ui/src/contexts/auth.jsx
  bugtracker-ui/src/contexts/open.jsx
  bugtracker-ui/src/contexts/statistics.jsx
  bugtracker-ui/src/contexts/team.jsx
  bugtracker-ui/src/contexts/ticket.jsx
  bugtracker-ui/src/hooks/useLoginForm.js
  bugtracker-ui/src/hooks/useProjectForm.js
  bugtracker-ui/src/hooks/useTicketForm.js
  bugtracker-ui/src/services/charts.js
Labels: bug

#119 Css final fixes
  bugtracker-ui/src/components/App/App.jsx
  bugtracker-ui/src/components/Dashboard/Dashboard.css
  bugtracker-ui/src/components/Dashboard/Dashboard.jsx
  bugtracker-ui/src/components/Modals/ProjectModal/ProjectModal.css
  bugtracker-ui/src/components/Modals/SelectProjecctModal/SelectProjectModal.css
  bugtracker-ui/src/components/Modals/SelectProjecctModal/SelectProjectModal.jsx
  bugtracker-ui/src/components/Modals/TeamModal/TeamModal.css
  bugtracker-ui/src/components/Modals/TicketModal/TicketModal.css
  bugtracker-ui/src/components/Navbar/Navbar.css
  bugtracker-ui/src/components/Navbar/Navbar.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectCard/ProjectCard.css
  bugtracker-ui/src/components/ProjectsPage/ProjectCard/ProjectCard.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectsOverview/ProjectsOverview.css
  bugtracker-ui/src/components/ProjectsPage/ProjectsOverview/ProjectsOverview.jsx
  bugtracker-ui/src/components/ProjectsPage/ProjectsPage.css
  bugtracker-ui/src/components/Sidebar/Sidebar.css
  bugtracker-ui/src/components/Tables/ProjectsPageTicketsTable.jsx
  bugtracker-ui/src/components/TeamsPage/TeamCard/TeamCard.css
  bugtracker-ui/src/components/TeamsPage/TeamView/TeamView.css
  bugtracker-ui/src/components/TeamsPage/TeamView/TeamView.jsx
  bugtracker-ui/src/components/TeamsPage/TeamsOverview/TeamsOverview.css
  bugtracker-ui/src/components/TeamsPage/TeamsOverview/TeamsOverview.jsx
  bugtracker-ui/src/components/TeamsPage/TeamsPage.css
  bugtracker-ui/src/components/TicketsPage/TicketCard/TicketCard.css
  bugtracker-ui/src/components/TicketsPage/TicketCard/TicketCard.jsx
  bugtracker-ui/src/components/TicketsPage/TicketView/TicketView.css
  bugtracker-ui/src/components/TicketsPage/TicketView/TicketView.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsOverview/TicketsOverview.css
  bugtracker-ui/src/components/TicketsPage/TicketsOverview/TicketsOverview.jsx
  bugtracker-ui/src/components/TicketsPage/TicketsPage.css
  bugtracker-ui/src/components/UserProfile/UserProfile.css
  bugtracker-ui/src/contexts/statistics.jsx
  bugtracker-ui/src/services/charts.js
Labels: enhancement

#121 Changed sidebar icon order
  bugtracker-ui/src/components/Sidebar/Sidebar.jsx
Labels: enhancement
